version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-algafood
    restart: always
    environment:
      - MYSQL_DATABASE=algafood
      - MYSQL_ROOT_PASSWORD=myroot
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local