version: '3'

services:
  mysql-server-db:
    container_name: mysql-server-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: algafood
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql